In [109]:
#Multi Layer Perceptron for Binary Classification
import tensorflow as tf
from matplotlib import pyplot
import numpy as np
import pandas as pd
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import InputLayer
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import confusion_matrix
import time
import os
import tempfile

In [110]:
#Load the Dataset
path = 'raw_mosaic_pixeldata_NN.csv'
df = read_csv(path, header=None)
print(df)

            0         1         2         3         4         5         6    \
0      0.015129  0.017095  0.019158  0.020151  0.020051  0.020037  0.020417   
1      0.021492  0.021839  0.022099  0.021414  0.019458  0.017557  0.017055   
2      0.018931  0.018543  0.018299  0.017018  0.014979  0.014023  0.015348   
3      0.017672  0.017455  0.017240  0.016048  0.014647  0.014277  0.015218   
4      0.019671  0.020411  0.020497  0.020230  0.021146  0.022208  0.022273   
...         ...       ...       ...       ...       ...       ...       ...   
36063  0.020789  0.019660  0.020122  0.021130  0.020752  0.018410  0.015181   
36064  0.036120  0.034278  0.034476  0.035099  0.034775  0.034062  0.033057   
36065  0.040596  0.039176  0.036893  0.034860  0.033695  0.032679  0.031467   
36066  0.037533  0.036553  0.034959  0.032973  0.031371  0.030838  0.031487   
36067  0.045737  0.040986  0.035687  0.031960  0.030897  0.031809  0.033327   

            7         8         9    ...       758 

In [111]:
#Load the Feature Selected Bands

feature_path = 'ETC_RFE_ANOVA.csv'
feature_df = read_csv(feature_path, header=None)
feature_array_triple = feature_df.to_numpy()
print(feature_array_triple)

feature_path = '12_features.csv'
feature_df = read_csv(feature_path, header=None)
feature_array_twelve = feature_df.to_numpy()
print(feature_array_twelve)

feature_path = 'LIT_Bands_Intersection_Feature_Selection.csv'
feature_df = read_csv(feature_path, header=None)
feature_array_LIT_intersect = feature_df.to_numpy()
print(feature_array_LIT_intersect)

feature_path = 'Literature_Bands_61.csv'
feature_df = read_csv(feature_path, header=None)
feature_array_LIT_61 = feature_df.to_numpy()
print(feature_array_LIT_61.size)

#Function used to return just the values in the list, can be used for 104 and 12 feature lists
def array_values(list):
    for i in list:
        return i

[[ 24  25  26  27  28  29  30  31  32  33  34  35  78  79  81  82  84  86
   87  88  89  91  92  93 155 156 157 158 159 160 161 162 163 164 165 166
  167 168 169 170 171 172 173 186 187 188 189 191 192 193 194 196 197 198
  199 200 201 203 204 205 206 207 208 210 281 283 284 290 292 293 306 309
  313 319 321 327 330 331 336 337 338 619 620 621 622 623 624 710 714 718
  719 721 727 732 735 738 743 744 747 749 751 758 759 766]]
[[164 165 166 189 191 192 193 196 199 200 203 204]]
[[ 79  82  87  88  89 167 168 169 170 171 196 197 620 622 624 727]]
61


In [112]:
#Split into input/output columns
#:-1
#array_values(list)-1

X, y = df.values[:, array_values(feature_array_triple)-1], df.values[:, -1]
print(X)
print(y)

[[0.024323406 0.024786333 0.025557835 ... 0.07704927 0.078165427
  0.074911892]
 [0.017354405 0.017653821 0.018485628 ... 0.050072946 0.051070999
  0.047248427]
 [0.014408262 0.014687239 0.015662696 ... 0.051737711 0.052510031
  0.051437993]
 ...
 [0.032839824 0.035231948 0.037352055 ... -0.006028205 -0.005399798
  -0.023646984]
 [0.034997389 0.037384901 0.040153164 ... 0.047700714 0.048524681
  0.031022113]
 [0.041136507 0.043989088 0.046262812 ... 0.071768932 0.072871484
  0.059392739]]
['green' 'green' 'green' ... 'blue' 'blue' 'blue']


In [113]:
#Ensure Data are Floats
X = X.astype('float32')

In [114]:
#Encode Strings to integers
y = LabelEncoder().fit_transform(y)
print(y)

[1 1 1 ... 0 0 0]


In [115]:
#Split into Training and Test Datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=17)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

#use same randomState

(25247, 104) (10821, 104) (25247,) (10821,)


In [116]:
#Determine number of input features
n_features = X_train.shape[1]
print(n_features)

104


In [118]:
print(initial_weights)

/tmp/tmpphlw28ga/initial_weights


In [117]:
#Define Model
N = 100
model = Sequential()
model.add(InputLayer(input_shape=(n_features,)))
model.add(Dense(N, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(2*N, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(3*N, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(2*N, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(1, activation='sigmoid'))

model.load_weights(initial_weights)

#100, 200, 300, 200, 1
#50, 100, 150, 100, 1
#25, 50, 75, 50, 1
#intial starting weights https://www.tensorflow.org/tutorials/structured_data/imbalanced_data#checkpoint_the_initial_weights
#model.summary()

ValueError: Shapes (104, 100) and (767, 100) are incompatible

In [ ]:
#Compile Model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy', 'AUC', 'Precision', 'Recall'])
model.summary()

In [ ]:
#Fit Model
start_time = time.time()
history = model.fit(X_train, y_train, epochs=100, batch_size=300, validation_split=0.3)
#initial_weights = os.path.join(tempfile.mkdtemp(), 'initial_weights')
#model.save_weights(initial_weights)
print(initial_weights)
end_time = time.time()


In [ ]:
#Save the Model
model.save('3FeatureAlgorithm_100200300_model.h5')

In [ ]:
#Evaluate the Model
loss, accuracy, auc, precision, recall  = model.evaluate(X_test, y_test, verbose=0)
print('Test Loss: %.3f' % loss)
print('Test Accuracy: %.3f' % accuracy)
print('Test AUC: %.3f' % auc)
print('Test Precision: %.3f' % precision)
print('Test Recall: %.3f' % recall)
print(end_time - start_time)

#confusionmatrix

y_pred = model.predict(X_test)
y_pred = np.round(y_pred).tolist()
#y_pred = np.argmax(y_pred, axis=1).tolist()

confusion_matrix(y_test, y_pred)

In [ ]:
#Output to a CSV
hist_df = pd.DataFrame(history.history)

hist_csv_file = '3FeatureAlgorithm_100200300_Output.csv'
with open(hist_csv_file, mode='w') as f:
    hist_df.to_csv(f)

In [ ]:
#Plot Learning Curves
fig_loss = pyplot.figure("Figure 1")
pyplot.title('Learning Curves')
pyplot.xlabel('Epoch')
pyplot.ylabel('Cross Entropy')
pyplot.plot(history.history['loss'], label='train')
pyplot.plot(history.history['val_loss'], label='val')
pyplot.legend()

fig_accuracy = pyplot.figure("Figure 2")
pyplot.xlabel('Epoch')
pyplot.ylabel('Accuracy')
pyplot.plot(history.history['accuracy'], label='accuracy')
pyplot.plot(history.history['val_accuracy'], label='val_accuracy')
pyplot.legend()

fig_auc = pyplot.figure("Figure 3")
pyplot.xlabel('Epoch')
pyplot.ylabel('AUC')
pyplot.plot(history.history['auc'], label='auc')
pyplot.plot(history.history['val_auc'], label='val_auc')
pyplot.legend()

fig_precision_recall = pyplot.figure("Figure 4")
pyplot.xlabel('Epoch')
pyplot.ylabel('Precision')
pyplot.plot(history.history['precision'], label='precision')
pyplot.plot(history.history['val_precision'], label='val_precision')

pyplot.legend()

fig_precision_recall = pyplot.figure("Figure 5")
pyplot.xlabel('Epoch')
pyplot.ylabel('Recall')
pyplot.plot(history.history['recall'], label='recall')
pyplot.plot(history.history['val_recall'], label='val_recall')
pyplot.legend()
pyplot.show()